// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/cs-java-share/CommonProto.proto

package gameserver.network.protos.game;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gameserver.network.protos.game.PLATFORM_TYPE}
   *
   * <pre>
   *设备平台
   * </pre>
   */
  public enum PLATFORM_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     *
     * <pre>
     *无操作系统
     * </pre>
     */
    NONE(0, 0),
    /**
     * <code>WINDOWS = 1;</code>
     *
     * <pre>
     *Windows平台
     * </pre>
     */
    WINDOWS(1, 1),
    /**
     * <code>LINUX = 2;</code>
     *
     * <pre>
     *Linux平台
     * </pre>
     */
    LINUX(2, 2),
    /**
     * <code>MAC = 3;</code>
     *
     * <pre>
     *Mac系统
     * </pre>
     */
    MAC(3, 3),
    /**
     * <code>WEB_PLAYER = 4;</code>
     *
     * <pre>
     *web平台
     * </pre>
     */
    WEB_PLAYER(4, 4),
    /**
     * <code>IOS = 5;</code>
     *
     * <pre>
     *IOS平台 iPhone或iPad
     * </pre>
     */
    IOS(5, 5),
    /**
     * <code>ANDROID = 6;</code>
     *
     * <pre>
     *安卓平台
     * </pre>
     */
    ANDROID(6, 6),
    /**
     * <code>WINDOWS_PHONE = 7;</code>
     *
     * <pre>
     *Windows Phone平台
     * </pre>
     */
    WINDOWS_PHONE(7, 7),
    /**
     * <code>BLACK_BERRY = 8;</code>
     *
     * <pre>
     *黑莓操作系统
     * </pre>
     */
    BLACK_BERRY(8, 8),
    /**
     * <code>OTHER = 9;</code>
     *
     * <pre>
     *其他操作系统
     * </pre>
     */
    OTHER(9, 9),
    ;

    /**
     * <code>NONE = 0;</code>
     *
     * <pre>
     *无操作系统
     * </pre>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>WINDOWS = 1;</code>
     *
     * <pre>
     *Windows平台
     * </pre>
     */
    public static final int WINDOWS_VALUE = 1;
    /**
     * <code>LINUX = 2;</code>
     *
     * <pre>
     *Linux平台
     * </pre>
     */
    public static final int LINUX_VALUE = 2;
    /**
     * <code>MAC = 3;</code>
     *
     * <pre>
     *Mac系统
     * </pre>
     */
    public static final int MAC_VALUE = 3;
    /**
     * <code>WEB_PLAYER = 4;</code>
     *
     * <pre>
     *web平台
     * </pre>
     */
    public static final int WEB_PLAYER_VALUE = 4;
    /**
     * <code>IOS = 5;</code>
     *
     * <pre>
     *IOS平台 iPhone或iPad
     * </pre>
     */
    public static final int IOS_VALUE = 5;
    /**
     * <code>ANDROID = 6;</code>
     *
     * <pre>
     *安卓平台
     * </pre>
     */
    public static final int ANDROID_VALUE = 6;
    /**
     * <code>WINDOWS_PHONE = 7;</code>
     *
     * <pre>
     *Windows Phone平台
     * </pre>
     */
    public static final int WINDOWS_PHONE_VALUE = 7;
    /**
     * <code>BLACK_BERRY = 8;</code>
     *
     * <pre>
     *黑莓操作系统
     * </pre>
     */
    public static final int BLACK_BERRY_VALUE = 8;
    /**
     * <code>OTHER = 9;</code>
     *
     * <pre>
     *其他操作系统
     * </pre>
     */
    public static final int OTHER_VALUE = 9;


    public final int getNumber() { return value; }

    public static PLATFORM_TYPE valueOf(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return WINDOWS;
        case 2: return LINUX;
        case 3: return MAC;
        case 4: return WEB_PLAYER;
        case 5: return IOS;
        case 6: return ANDROID;
        case 7: return WINDOWS_PHONE;
        case 8: return BLACK_BERRY;
        case 9: return OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PLATFORM_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PLATFORM_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PLATFORM_TYPE>() {
            public PLATFORM_TYPE findValueByNumber(int number) {
              return PLATFORM_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final PLATFORM_TYPE[] VALUES = values();

    public static PLATFORM_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PLATFORM_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gameserver.network.protos.game.PLATFORM_TYPE)
  }

  /**
   * Protobuf enum {@code gameserver.network.protos.game.Proto_BuildState}
   *
   * <pre>
   *建筑状态
   * </pre>
   */
  public enum Proto_BuildState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE_BUILD = 1;</code>
     *
     * <pre>
     *普通状态
     * </pre>
     */
    NONE_BUILD(0, 1),
    /**
     * <code>UPGRADE = 2;</code>
     *
     * <pre>
     *正在升级
     * </pre>
     */
    UPGRADE(1, 2),
    /**
     * <code>OPERATE = 3;</code>
     *
     * <pre>
     *正在产兵，升级科技等建筑特有的操作
     * </pre>
     */
    OPERATE(2, 3),
    /**
     * <code>OPERATE_UPGRADE = 4;</code>
     *
     * <pre>
     *产兵，升级科技等建筑特有的操作 过程中 点击升级  这些特有操作要暂停
     * </pre>
     */
    OPERATE_UPGRADE(3, 4),
    ;

    /**
     * <code>NONE_BUILD = 1;</code>
     *
     * <pre>
     *普通状态
     * </pre>
     */
    public static final int NONE_BUILD_VALUE = 1;
    /**
     * <code>UPGRADE = 2;</code>
     *
     * <pre>
     *正在升级
     * </pre>
     */
    public static final int UPGRADE_VALUE = 2;
    /**
     * <code>OPERATE = 3;</code>
     *
     * <pre>
     *正在产兵，升级科技等建筑特有的操作
     * </pre>
     */
    public static final int OPERATE_VALUE = 3;
    /**
     * <code>OPERATE_UPGRADE = 4;</code>
     *
     * <pre>
     *产兵，升级科技等建筑特有的操作 过程中 点击升级  这些特有操作要暂停
     * </pre>
     */
    public static final int OPERATE_UPGRADE_VALUE = 4;


    public final int getNumber() { return value; }

    public static Proto_BuildState valueOf(int value) {
      switch (value) {
        case 1: return NONE_BUILD;
        case 2: return UPGRADE;
        case 3: return OPERATE;
        case 4: return OPERATE_UPGRADE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Proto_BuildState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Proto_BuildState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Proto_BuildState>() {
            public Proto_BuildState findValueByNumber(int number) {
              return Proto_BuildState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final Proto_BuildState[] VALUES = values();

    public static Proto_BuildState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Proto_BuildState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gameserver.network.protos.game.Proto_BuildState)
  }

  /**
   * Protobuf enum {@code gameserver.network.protos.game.Proto_Off_Line}
   *
   * <pre>
   *建筑状态
   * </pre>
   */
  public enum Proto_Off_Line
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LEGION_LV = 1;</code>
     *
     * <pre>
     *军团等级
     * </pre>
     */
    LEGION_LV(0, 1),
    /**
     * <code>FEAT_VAL = 2;</code>
     *
     * <pre>
     *功勋值
     * </pre>
     */
    FEAT_VAL(1, 2),
    /**
     * <code>VIP_LV = 3;</code>
     *
     * <pre>
     *VIP等级
     * </pre>
     */
    VIP_LV(2, 3),
    ;

    /**
     * <code>LEGION_LV = 1;</code>
     *
     * <pre>
     *军团等级
     * </pre>
     */
    public static final int LEGION_LV_VALUE = 1;
    /**
     * <code>FEAT_VAL = 2;</code>
     *
     * <pre>
     *功勋值
     * </pre>
     */
    public static final int FEAT_VAL_VALUE = 2;
    /**
     * <code>VIP_LV = 3;</code>
     *
     * <pre>
     *VIP等级
     * </pre>
     */
    public static final int VIP_LV_VALUE = 3;


    public final int getNumber() { return value; }

    public static Proto_Off_Line valueOf(int value) {
      switch (value) {
        case 1: return LEGION_LV;
        case 2: return FEAT_VAL;
        case 3: return VIP_LV;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Proto_Off_Line>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Proto_Off_Line>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Proto_Off_Line>() {
            public Proto_Off_Line findValueByNumber(int number) {
              return Proto_Off_Line.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final Proto_Off_Line[] VALUES = values();

    public static Proto_Off_Line valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Proto_Off_Line(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gameserver.network.protos.game.Proto_Off_Line)
  }

  /**
   * Protobuf enum {@code gameserver.network.protos.game.Rebound_event_type}
   */
  public enum Rebound_event_type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET_MAIL = 1;</code>
     */
    GET_MAIL(0, 1),
    ;

    /**
     * <code>GET_MAIL = 1;</code>
     */
    public static final int GET_MAIL_VALUE = 1;


    public final int getNumber() { return value; }

    public static Rebound_event_type valueOf(int value) {
      switch (value) {
        case 1: return GET_MAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Rebound_event_type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Rebound_event_type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Rebound_event_type>() {
            public Rebound_event_type findValueByNumber(int number) {
              return Rebound_event_type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.getDescriptor().getEnumTypes().get(3);
    }

    private static final Rebound_event_type[] VALUES = values();

    public static Rebound_event_type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Rebound_event_type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gameserver.network.protos.game.Rebound_event_type)
  }

  public interface Msg_C2G_ReboundOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    boolean hasEventType();
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    gameserver.network.protos.game.CommonProto.Rebound_event_type getEventType();
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.Msg_C2G_Rebound}
   *
   * <pre>
   * 服务器客户端反弹协议, 客户端不需要理解，接到后马上会包就行
   * </pre>
   */
  public static final class Msg_C2G_Rebound extends
      com.google.protobuf.GeneratedMessage
      implements Msg_C2G_ReboundOrBuilder {
    // Use Msg_C2G_Rebound.newBuilder() to construct.
    private Msg_C2G_Rebound(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_C2G_Rebound(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_C2G_Rebound defaultInstance;
    public static Msg_C2G_Rebound getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_C2G_Rebound getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_C2G_Rebound(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gameserver.network.protos.game.CommonProto.Rebound_event_type value = gameserver.network.protos.game.CommonProto.Rebound_event_type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                eventType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.class, gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_C2G_Rebound> PARSER =
        new com.google.protobuf.AbstractParser<Msg_C2G_Rebound>() {
      public Msg_C2G_Rebound parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_C2G_Rebound(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_C2G_Rebound> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;
    public static final int EVENTTYPE_FIELD_NUMBER = 1;
    private gameserver.network.protos.game.CommonProto.Rebound_event_type eventType_;
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    public gameserver.network.protos.game.CommonProto.Rebound_event_type getEventType() {
      return eventType_;
    }

    private void initFields() {
      eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, eventType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eventType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_C2G_Rebound}
     *
     * <pre>
     * 服务器客户端反弹协议, 客户端不需要理解，接到后马上会包就行
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.CommonProto.Msg_C2G_ReboundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.class, gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.Builder.class);
      }

      // Construct using gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_descriptor;
      }

      public gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound getDefaultInstanceForType() {
        return gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.getDefaultInstance();
      }

      public gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound build() {
        gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound buildPartial() {
        gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound result = new gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eventType_ = eventType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound) {
          return mergeFrom((gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound other) {
        if (other == gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound.getDefaultInstance()) return this;
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.CommonProto.Msg_C2G_Rebound) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;
      private gameserver.network.protos.game.CommonProto.Rebound_event_type eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public gameserver.network.protos.game.CommonProto.Rebound_event_type getEventType() {
        return eventType_;
      }
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public Builder setEventType(gameserver.network.protos.game.CommonProto.Rebound_event_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_C2G_Rebound)
    }

    static {
      defaultInstance = new Msg_C2G_Rebound(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_C2G_Rebound)
  }

  public interface Msg_G2C_ReboundOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    boolean hasEventType();
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    gameserver.network.protos.game.CommonProto.Rebound_event_type getEventType();
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_Rebound}
   */
  public static final class Msg_G2C_Rebound extends
      com.google.protobuf.GeneratedMessage
      implements Msg_G2C_ReboundOrBuilder {
    // Use Msg_G2C_Rebound.newBuilder() to construct.
    private Msg_G2C_Rebound(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_G2C_Rebound(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_G2C_Rebound defaultInstance;
    public static Msg_G2C_Rebound getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_G2C_Rebound getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_G2C_Rebound(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gameserver.network.protos.game.CommonProto.Rebound_event_type value = gameserver.network.protos.game.CommonProto.Rebound_event_type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                eventType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.class, gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_G2C_Rebound> PARSER =
        new com.google.protobuf.AbstractParser<Msg_G2C_Rebound>() {
      public Msg_G2C_Rebound parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_G2C_Rebound(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_G2C_Rebound> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;
    public static final int EVENTTYPE_FIELD_NUMBER = 1;
    private gameserver.network.protos.game.CommonProto.Rebound_event_type eventType_;
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
     */
    public gameserver.network.protos.game.CommonProto.Rebound_event_type getEventType() {
      return eventType_;
    }

    private void initFields() {
      eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, eventType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eventType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_Rebound}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.CommonProto.Msg_G2C_ReboundOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.class, gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.Builder.class);
      }

      // Construct using gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_descriptor;
      }

      public gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound getDefaultInstanceForType() {
        return gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.getDefaultInstance();
      }

      public gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound build() {
        gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound buildPartial() {
        gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound result = new gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eventType_ = eventType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound) {
          return mergeFrom((gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound other) {
        if (other == gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound.getDefaultInstance()) return this;
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.CommonProto.Msg_G2C_Rebound) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;
      private gameserver.network.protos.game.CommonProto.Rebound_event_type eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public gameserver.network.protos.game.CommonProto.Rebound_event_type getEventType() {
        return eventType_;
      }
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public Builder setEventType(gameserver.network.protos.game.CommonProto.Rebound_event_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gameserver.network.protos.game.Rebound_event_type eventType = 1;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = gameserver.network.protos.game.CommonProto.Rebound_event_type.GET_MAIL;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_G2C_Rebound)
    }

    static {
      defaultInstance = new Msg_G2C_Rebound(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_G2C_Rebound)
  }

  public interface Msg_S2G_NoticeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 playerId = 1;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    long getPlayerId();

    // optional int32 type = 2;
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     *PromptType id
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     *PromptType id
     * </pre>
     */
    int getType();
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.Msg_S2G_Notice}
   *
   * <pre>
   *PromptType通告基础值非枚举
   * </pre>
   */
  public static final class Msg_S2G_Notice extends
      com.google.protobuf.GeneratedMessage
      implements Msg_S2G_NoticeOrBuilder {
    // Use Msg_S2G_Notice.newBuilder() to construct.
    private Msg_S2G_Notice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_S2G_Notice(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_S2G_Notice defaultInstance;
    public static Msg_S2G_Notice getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_S2G_Notice getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_S2G_Notice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_Notice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_Notice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.class, gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_S2G_Notice> PARSER =
        new com.google.protobuf.AbstractParser<Msg_S2G_Notice>() {
      public Msg_S2G_Notice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_S2G_Notice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_S2G_Notice> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    // optional int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     *PromptType id
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     *PromptType id
     * </pre>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      playerId_ = 0L;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.CommonProto.Msg_S2G_Notice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_S2G_Notice}
     *
     * <pre>
     *PromptType通告基础值非枚举
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.CommonProto.Msg_S2G_NoticeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_Notice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_Notice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.class, gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.Builder.class);
      }

      // Construct using gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_Notice_descriptor;
      }

      public gameserver.network.protos.game.CommonProto.Msg_S2G_Notice getDefaultInstanceForType() {
        return gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.getDefaultInstance();
      }

      public gameserver.network.protos.game.CommonProto.Msg_S2G_Notice build() {
        gameserver.network.protos.game.CommonProto.Msg_S2G_Notice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.CommonProto.Msg_S2G_Notice buildPartial() {
        gameserver.network.protos.game.CommonProto.Msg_S2G_Notice result = new gameserver.network.protos.game.CommonProto.Msg_S2G_Notice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.CommonProto.Msg_S2G_Notice) {
          return mergeFrom((gameserver.network.protos.game.CommonProto.Msg_S2G_Notice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.CommonProto.Msg_S2G_Notice other) {
        if (other == gameserver.network.protos.game.CommonProto.Msg_S2G_Notice.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.CommonProto.Msg_S2G_Notice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.CommonProto.Msg_S2G_Notice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 playerId = 1;
      private long playerId_ ;
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 type = 2;
      private int type_ ;
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *PromptType id
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *PromptType id
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *PromptType id
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 2;</code>
       *
       * <pre>
       *PromptType id
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_S2G_Notice)
    }

    static {
      defaultInstance = new Msg_S2G_Notice(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_S2G_Notice)
  }

  public interface Msg_S2G_UpdateTableOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string table_name = 1;
    /**
     * <code>repeated string table_name = 1;</code>
     */
    java.util.List<java.lang.String>
    getTableNameList();
    /**
     * <code>repeated string table_name = 1;</code>
     */
    int getTableNameCount();
    /**
     * <code>repeated string table_name = 1;</code>
     */
    java.lang.String getTableName(int index);
    /**
     * <code>repeated string table_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes(int index);
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.Msg_S2G_UpdateTable}
   *
   * <pre>
   *更新table文件消息
   * </pre>
   */
  public static final class Msg_S2G_UpdateTable extends
      com.google.protobuf.GeneratedMessage
      implements Msg_S2G_UpdateTableOrBuilder {
    // Use Msg_S2G_UpdateTable.newBuilder() to construct.
    private Msg_S2G_UpdateTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_S2G_UpdateTable(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_S2G_UpdateTable defaultInstance;
    public static Msg_S2G_UpdateTable getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_S2G_UpdateTable getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_S2G_UpdateTable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                tableName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              tableName_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          tableName_ = new com.google.protobuf.UnmodifiableLazyStringList(tableName_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.class, gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_S2G_UpdateTable> PARSER =
        new com.google.protobuf.AbstractParser<Msg_S2G_UpdateTable>() {
      public Msg_S2G_UpdateTable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_S2G_UpdateTable(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_S2G_UpdateTable> getParserForType() {
      return PARSER;
    }

    // repeated string table_name = 1;
    public static final int TABLE_NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList tableName_;
    /**
     * <code>repeated string table_name = 1;</code>
     */
    public java.util.List<java.lang.String>
        getTableNameList() {
      return tableName_;
    }
    /**
     * <code>repeated string table_name = 1;</code>
     */
    public int getTableNameCount() {
      return tableName_.size();
    }
    /**
     * <code>repeated string table_name = 1;</code>
     */
    public java.lang.String getTableName(int index) {
      return tableName_.get(index);
    }
    /**
     * <code>repeated string table_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes(int index) {
      return tableName_.getByteString(index);
    }

    private void initFields() {
      tableName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < tableName_.size(); i++) {
        output.writeBytes(1, tableName_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < tableName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tableName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTableNameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_S2G_UpdateTable}
     *
     * <pre>
     *更新table文件消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.class, gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.Builder.class);
      }

      // Construct using gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tableName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.CommonProto.internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_descriptor;
      }

      public gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable getDefaultInstanceForType() {
        return gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.getDefaultInstance();
      }

      public gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable build() {
        gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable buildPartial() {
        gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable result = new gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tableName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              tableName_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tableName_ = tableName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable) {
          return mergeFrom((gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable other) {
        if (other == gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable.getDefaultInstance()) return this;
        if (!other.tableName_.isEmpty()) {
          if (tableName_.isEmpty()) {
            tableName_ = other.tableName_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTableNameIsMutable();
            tableName_.addAll(other.tableName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.CommonProto.Msg_S2G_UpdateTable) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string table_name = 1;
      private com.google.protobuf.LazyStringList tableName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTableNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tableName_ = new com.google.protobuf.LazyStringArrayList(tableName_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public java.util.List<java.lang.String>
          getTableNameList() {
        return java.util.Collections.unmodifiableList(tableName_);
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public int getTableNameCount() {
        return tableName_.size();
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public java.lang.String getTableName(int index) {
        return tableName_.get(index);
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes(int index) {
        return tableName_.getByteString(index);
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public Builder setTableName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTableNameIsMutable();
        tableName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public Builder addTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTableNameIsMutable();
        tableName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public Builder addAllTableName(
          java.lang.Iterable<java.lang.String> values) {
        ensureTableNameIsMutable();
        super.addAll(values, tableName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public Builder clearTableName() {
        tableName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string table_name = 1;</code>
       */
      public Builder addTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTableNameIsMutable();
        tableName_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_S2G_UpdateTable)
    }

    static {
      defaultInstance = new Msg_S2G_UpdateTable(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_S2G_UpdateTable)
  }
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_S2G_Notice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_S2G_Notice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$game/cs-java-share/CommonProto.proto\022\036" +
      "gameserver.network.protos.game\"X\n\017Msg_C2" +
      "G_Rebound\022E\n\teventType\030\001 \001(\01622.gameserve" +
      "r.network.protos.game.Rebound_event_type" +
      "\"X\n\017Msg_G2C_Rebound\022E\n\teventType\030\001 \001(\01622" +
      ".gameserver.network.protos.game.Rebound_" +
      "event_type\"0\n\016Msg_S2G_Notice\022\020\n\010playerId" +
      "\030\001 \001(\003\022\014\n\004type\030\002 \001(\005*\217\001\n\rPLATFORM_TYPE\022\010" +
      "\n\004NONE\020\000\022\013\n\007WINDOWS\020\001\022\t\n\005LINUX\020\002\022\007\n\003MAC\020" +
      "\003\022\016\n\nWEB_PLAYER\020\004\022\007\n\003IOS\020\005\022\013\n\007ANDROID\020\006\022",
      "\021\n\rWINDOWS_PHONE\020\007\022\017\n\013BLACK_BERRY\020\010\022\t\n\005O" +
      "THER\020\t*Q\n\020Proto_BuildState\022\016\n\nNONE_BUILD" +
      "\020\001\022\013\n\007UPGRADE\020\002\022\013\n\007OPERATE\020\003\022\023\n\017OPERATE_" +
      "UPGRADE\020\004*9\n\016Proto_Off_Line\022\r\n\tLEGION_LV" +
      "\020\001\022\014\n\010FEAT_VAL\020\002\022\n\n\006VIP_LV\020\003*\"\n\022Rebound_" +
      "event_type\022\014\n\010GET_MAIL\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_C2G_Rebound_descriptor,
              new java.lang.String[] { "EventType", });
          internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_G2C_Rebound_descriptor,
              new java.lang.String[] { "EventType", });
          internal_static_gameserver_network_protos_game_Msg_S2G_Notice_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gameserver_network_protos_game_Msg_S2G_Notice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_S2G_Notice_descriptor,
              new java.lang.String[] { "PlayerId", "Type", });
          internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_S2G_UpdateTable_descriptor,
              new java.lang.String[] { "TableName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
