// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/cs-java/ProFormation.proto

package gameserver.network.protos.game;

public final class ProFormation {
  private ProFormation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gameserver.network.protos.game.EnumFormation}
   */
  public enum EnumFormation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FORMATION1 = 1;</code>
     *
     * <pre>
     *阵形1
     * </pre>
     */
    FORMATION1(0, 1),
    /**
     * <code>FORMATION2 = 2;</code>
     *
     * <pre>
     *阵形2
     * </pre>
     */
    FORMATION2(1, 2),
    /**
     * <code>DEFENSE = 3;</code>
     *
     * <pre>
     *防御阵形
     * </pre>
     */
    DEFENSE(2, 3),
    ;

    /**
     * <code>FORMATION1 = 1;</code>
     *
     * <pre>
     *阵形1
     * </pre>
     */
    public static final int FORMATION1_VALUE = 1;
    /**
     * <code>FORMATION2 = 2;</code>
     *
     * <pre>
     *阵形2
     * </pre>
     */
    public static final int FORMATION2_VALUE = 2;
    /**
     * <code>DEFENSE = 3;</code>
     *
     * <pre>
     *防御阵形
     * </pre>
     */
    public static final int DEFENSE_VALUE = 3;


    public final int getNumber() { return value; }

    public static EnumFormation valueOf(int value) {
      switch (value) {
        case 1: return FORMATION1;
        case 2: return FORMATION2;
        case 3: return DEFENSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumFormation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EnumFormation>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumFormation>() {
            public EnumFormation findValueByNumber(int number) {
              return EnumFormation.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gameserver.network.protos.game.ProFormation.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumFormation[] VALUES = values();

    public static EnumFormation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EnumFormation(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gameserver.network.protos.game.EnumFormation)
  }

  public interface MSG_C_SAVEFORMATIONOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .gameserver.network.protos.game.EnumFormation type = 1;
    /**
     * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    gameserver.network.protos.game.ProFormation.EnumFormation getType();

    // repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    java.util.List<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo> 
        getFormationInfoList();
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo getFormationInfo(int index);
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    int getFormationInfoCount();
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    java.util.List<? extends gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder> 
        getFormationInfoOrBuilderList();
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder getFormationInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.MSG_C_SAVEFORMATION}
   *
   * <pre>
   * 保存阵形
   * </pre>
   */
  public static final class MSG_C_SAVEFORMATION extends
      com.google.protobuf.GeneratedMessage
      implements MSG_C_SAVEFORMATIONOrBuilder {
    // Use MSG_C_SAVEFORMATION.newBuilder() to construct.
    private MSG_C_SAVEFORMATION(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MSG_C_SAVEFORMATION(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MSG_C_SAVEFORMATION defaultInstance;
    public static MSG_C_SAVEFORMATION getDefaultInstance() {
      return defaultInstance;
    }

    public MSG_C_SAVEFORMATION getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MSG_C_SAVEFORMATION(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gameserver.network.protos.game.ProFormation.EnumFormation value = gameserver.network.protos.game.ProFormation.EnumFormation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                formationInfo_ = new java.util.ArrayList<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              formationInfo_.add(input.readMessage(gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          formationInfo_ = java.util.Collections.unmodifiableList(formationInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.class, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.Builder.class);
    }

    public static com.google.protobuf.Parser<MSG_C_SAVEFORMATION> PARSER =
        new com.google.protobuf.AbstractParser<MSG_C_SAVEFORMATION>() {
      public MSG_C_SAVEFORMATION parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MSG_C_SAVEFORMATION(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MSG_C_SAVEFORMATION> getParserForType() {
      return PARSER;
    }

    public interface FormationInfoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 x = 1;
      /**
       * <code>required int32 x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required int32 x = 1;</code>
       */
      int getX();

      // required int32 y = 2;
      /**
       * <code>required int32 y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required int32 y = 2;</code>
       */
      int getY();

      // required int32 id = 3;
      /**
       * <code>required int32 id = 3;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 3;</code>
       */
      int getId();

      // required int32 type = 4;
      /**
       * <code>required int32 type = 4;</code>
       */
      boolean hasType();
      /**
       * <code>required int32 type = 4;</code>
       */
      int getType();
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo}
     */
    public static final class FormationInfo extends
        com.google.protobuf.GeneratedMessage
        implements FormationInfoOrBuilder {
      // Use FormationInfo.newBuilder() to construct.
      private FormationInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private FormationInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final FormationInfo defaultInstance;
      public static FormationInfo getDefaultInstance() {
        return defaultInstance;
      }

      public FormationInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private FormationInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                x_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                y_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                id_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                type_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.class, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder.class);
      }

      public static com.google.protobuf.Parser<FormationInfo> PARSER =
          new com.google.protobuf.AbstractParser<FormationInfo>() {
        public FormationInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FormationInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<FormationInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 x = 1;
      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }

      // required int32 y = 2;
      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }

      // required int32 id = 3;
      public static final int ID_FIELD_NUMBER = 3;
      private int id_;
      /**
       * <code>required int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }

      // required int32 type = 4;
      public static final int TYPE_FIELD_NUMBER = 4;
      private int type_;
      /**
       * <code>required int32 type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }

      private void initFields() {
        x_ = 0;
        y_ = 0;
        id_ = 0;
        type_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, id_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, type_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, id_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, type_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.class, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder.class);
        }

        // Construct using gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_descriptor;
        }

        public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo getDefaultInstanceForType() {
          return gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.getDefaultInstance();
        }

        public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo build() {
          gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo buildPartial() {
          gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo result = new gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo) {
            return mergeFrom((gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo other) {
          if (other == gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          if (!hasId()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 x = 1;
        private int x_ ;
        /**
         * <code>required int32 x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public int getX() {
          return x_;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder setX(int value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0;
          onChanged();
          return this;
        }

        // required int32 y = 2;
        private int y_ ;
        /**
         * <code>required int32 y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0;
          onChanged();
          return this;
        }

        // required int32 id = 3;
        private int id_ ;
        /**
         * <code>required int32 id = 3;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 id = 3;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 3;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000004;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 3;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          id_ = 0;
          onChanged();
          return this;
        }

        // required int32 type = 4;
        private int type_ ;
        /**
         * <code>required int32 type = 4;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int32 type = 4;</code>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>required int32 type = 4;</code>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000008;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 type = 4;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000008);
          type_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo)
      }

      static {
        defaultInstance = new FormationInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo)
    }

    private int bitField0_;
    // required .gameserver.network.protos.game.EnumFormation type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private gameserver.network.protos.game.ProFormation.EnumFormation type_;
    /**
     * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    public gameserver.network.protos.game.ProFormation.EnumFormation getType() {
      return type_;
    }

    // repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;
    public static final int FORMATIONINFO_FIELD_NUMBER = 2;
    private java.util.List<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo> formationInfo_;
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    public java.util.List<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo> getFormationInfoList() {
      return formationInfo_;
    }
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    public java.util.List<? extends gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder> 
        getFormationInfoOrBuilderList() {
      return formationInfo_;
    }
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    public int getFormationInfoCount() {
      return formationInfo_.size();
    }
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo getFormationInfo(int index) {
      return formationInfo_.get(index);
    }
    /**
     * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
     *
     * <pre>
     *阵形信息
     * </pre>
     */
    public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder getFormationInfoOrBuilder(
        int index) {
      return formationInfo_.get(index);
    }

    private void initFields() {
      type_ = gameserver.network.protos.game.ProFormation.EnumFormation.FORMATION1;
      formationInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFormationInfoCount(); i++) {
        if (!getFormationInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < formationInfo_.size(); i++) {
        output.writeMessage(2, formationInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      for (int i = 0; i < formationInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, formationInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.MSG_C_SAVEFORMATION}
     *
     * <pre>
     * 保存阵形
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATIONOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.class, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.Builder.class);
      }

      // Construct using gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFormationInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = gameserver.network.protos.game.ProFormation.EnumFormation.FORMATION1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (formationInfoBuilder_ == null) {
          formationInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          formationInfoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.ProFormation.internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor;
      }

      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION getDefaultInstanceForType() {
        return gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.getDefaultInstance();
      }

      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION build() {
        gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION buildPartial() {
        gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION result = new gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (formationInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            formationInfo_ = java.util.Collections.unmodifiableList(formationInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.formationInfo_ = formationInfo_;
        } else {
          result.formationInfo_ = formationInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION) {
          return mergeFrom((gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION other) {
        if (other == gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (formationInfoBuilder_ == null) {
          if (!other.formationInfo_.isEmpty()) {
            if (formationInfo_.isEmpty()) {
              formationInfo_ = other.formationInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFormationInfoIsMutable();
              formationInfo_.addAll(other.formationInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.formationInfo_.isEmpty()) {
            if (formationInfoBuilder_.isEmpty()) {
              formationInfoBuilder_.dispose();
              formationInfoBuilder_ = null;
              formationInfo_ = other.formationInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              formationInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFormationInfoFieldBuilder() : null;
            } else {
              formationInfoBuilder_.addAllMessages(other.formationInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getFormationInfoCount(); i++) {
          if (!getFormationInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .gameserver.network.protos.game.EnumFormation type = 1;
      private gameserver.network.protos.game.ProFormation.EnumFormation type_ = gameserver.network.protos.game.ProFormation.EnumFormation.FORMATION1;
      /**
       * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public gameserver.network.protos.game.ProFormation.EnumFormation getType() {
        return type_;
      }
      /**
       * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public Builder setType(gameserver.network.protos.game.ProFormation.EnumFormation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gameserver.network.protos.game.EnumFormation type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = gameserver.network.protos.game.ProFormation.EnumFormation.FORMATION1;
        onChanged();
        return this;
      }

      // repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;
      private java.util.List<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo> formationInfo_ =
        java.util.Collections.emptyList();
      private void ensureFormationInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          formationInfo_ = new java.util.ArrayList<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo>(formationInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder> formationInfoBuilder_;

      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public java.util.List<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo> getFormationInfoList() {
        if (formationInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(formationInfo_);
        } else {
          return formationInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public int getFormationInfoCount() {
        if (formationInfoBuilder_ == null) {
          return formationInfo_.size();
        } else {
          return formationInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo getFormationInfo(int index) {
        if (formationInfoBuilder_ == null) {
          return formationInfo_.get(index);
        } else {
          return formationInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder setFormationInfo(
          int index, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo value) {
        if (formationInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFormationInfoIsMutable();
          formationInfo_.set(index, value);
          onChanged();
        } else {
          formationInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder setFormationInfo(
          int index, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder builderForValue) {
        if (formationInfoBuilder_ == null) {
          ensureFormationInfoIsMutable();
          formationInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          formationInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder addFormationInfo(gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo value) {
        if (formationInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFormationInfoIsMutable();
          formationInfo_.add(value);
          onChanged();
        } else {
          formationInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder addFormationInfo(
          int index, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo value) {
        if (formationInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFormationInfoIsMutable();
          formationInfo_.add(index, value);
          onChanged();
        } else {
          formationInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder addFormationInfo(
          gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder builderForValue) {
        if (formationInfoBuilder_ == null) {
          ensureFormationInfoIsMutable();
          formationInfo_.add(builderForValue.build());
          onChanged();
        } else {
          formationInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder addFormationInfo(
          int index, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder builderForValue) {
        if (formationInfoBuilder_ == null) {
          ensureFormationInfoIsMutable();
          formationInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          formationInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder addAllFormationInfo(
          java.lang.Iterable<? extends gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo> values) {
        if (formationInfoBuilder_ == null) {
          ensureFormationInfoIsMutable();
          super.addAll(values, formationInfo_);
          onChanged();
        } else {
          formationInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder clearFormationInfo() {
        if (formationInfoBuilder_ == null) {
          formationInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          formationInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public Builder removeFormationInfo(int index) {
        if (formationInfoBuilder_ == null) {
          ensureFormationInfoIsMutable();
          formationInfo_.remove(index);
          onChanged();
        } else {
          formationInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder getFormationInfoBuilder(
          int index) {
        return getFormationInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder getFormationInfoOrBuilder(
          int index) {
        if (formationInfoBuilder_ == null) {
          return formationInfo_.get(index);  } else {
          return formationInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public java.util.List<? extends gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder> 
           getFormationInfoOrBuilderList() {
        if (formationInfoBuilder_ != null) {
          return formationInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(formationInfo_);
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder addFormationInfoBuilder() {
        return getFormationInfoFieldBuilder().addBuilder(
            gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder addFormationInfoBuilder(
          int index) {
        return getFormationInfoFieldBuilder().addBuilder(
            index, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .gameserver.network.protos.game.MSG_C_SAVEFORMATION.FormationInfo formationInfo = 2;</code>
       *
       * <pre>
       *阵形信息
       * </pre>
       */
      public java.util.List<gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder> 
           getFormationInfoBuilderList() {
        return getFormationInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder> 
          getFormationInfoFieldBuilder() {
        if (formationInfoBuilder_ == null) {
          formationInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfo.Builder, gameserver.network.protos.game.ProFormation.MSG_C_SAVEFORMATION.FormationInfoOrBuilder>(
                  formationInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          formationInfo_ = null;
        }
        return formationInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.MSG_C_SAVEFORMATION)
    }

    static {
      defaultInstance = new MSG_C_SAVEFORMATION(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.MSG_C_SAVEFORMATION)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037game/cs-java/ProFormation.proto\022\036games" +
      "erver.network.protos.game\"\355\001\n\023MSG_C_SAVE" +
      "FORMATION\022;\n\004type\030\001 \002(\0162-.gameserver.net" +
      "work.protos.game.EnumFormation\022X\n\rformat" +
      "ionInfo\030\002 \003(\0132A.gameserver.network.proto" +
      "s.game.MSG_C_SAVEFORMATION.FormationInfo" +
      "\032?\n\rFormationInfo\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\022" +
      "\n\n\002id\030\003 \002(\005\022\014\n\004type\030\004 \002(\005*<\n\rEnumFormati" +
      "on\022\016\n\nFORMATION1\020\001\022\016\n\nFORMATION2\020\002\022\013\n\007DE" +
      "FENSE\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor,
              new java.lang.String[] { "Type", "FormationInfo", });
          internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_descriptor =
            internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_descriptor.getNestedTypes().get(0);
          internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_MSG_C_SAVEFORMATION_FormationInfo_descriptor,
              new java.lang.String[] { "X", "Y", "Id", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
