// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/cs-java/ProPlayerChange.proto

package gameserver.network.protos.game;

public final class ProPlayerChange {
  private ProPlayerChange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Msg_G2C_Player_Val_ChangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 old_val = 1;
    /**
     * <code>required int32 old_val = 1;</code>
     *
     * <pre>
     *旧值
     * </pre>
     */
    boolean hasOldVal();
    /**
     * <code>required int32 old_val = 1;</code>
     *
     * <pre>
     *旧值
     * </pre>
     */
    int getOldVal();

    // required int32 new_val = 2;
    /**
     * <code>required int32 new_val = 2;</code>
     *
     * <pre>
     *新值
     * </pre>
     */
    boolean hasNewVal();
    /**
     * <code>required int32 new_val = 2;</code>
     *
     * <pre>
     *新值
     * </pre>
     */
    int getNewVal();

    // required .gameserver.network.protos.game.Proto_Off_Line type = 3;
    /**
     * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
     *
     * <pre>
     *类型 
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
     *
     * <pre>
     *类型 
     * </pre>
     */
    gameserver.network.protos.game.CommonProto.Proto_Off_Line getType();
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_Player_Val_Change}
   *
   * <pre>
   *玩家数据变化
   * </pre>
   */
  public static final class Msg_G2C_Player_Val_Change extends
      com.google.protobuf.GeneratedMessage
      implements Msg_G2C_Player_Val_ChangeOrBuilder {
    // Use Msg_G2C_Player_Val_Change.newBuilder() to construct.
    private Msg_G2C_Player_Val_Change(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_G2C_Player_Val_Change(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_G2C_Player_Val_Change defaultInstance;
    public static Msg_G2C_Player_Val_Change getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_G2C_Player_Val_Change getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_G2C_Player_Val_Change(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              oldVal_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              newVal_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              gameserver.network.protos.game.CommonProto.Proto_Off_Line value = gameserver.network.protos.game.CommonProto.Proto_Off_Line.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.ProPlayerChange.internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.ProPlayerChange.internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.class, gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_G2C_Player_Val_Change> PARSER =
        new com.google.protobuf.AbstractParser<Msg_G2C_Player_Val_Change>() {
      public Msg_G2C_Player_Val_Change parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_G2C_Player_Val_Change(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_G2C_Player_Val_Change> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 old_val = 1;
    public static final int OLD_VAL_FIELD_NUMBER = 1;
    private int oldVal_;
    /**
     * <code>required int32 old_val = 1;</code>
     *
     * <pre>
     *旧值
     * </pre>
     */
    public boolean hasOldVal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 old_val = 1;</code>
     *
     * <pre>
     *旧值
     * </pre>
     */
    public int getOldVal() {
      return oldVal_;
    }

    // required int32 new_val = 2;
    public static final int NEW_VAL_FIELD_NUMBER = 2;
    private int newVal_;
    /**
     * <code>required int32 new_val = 2;</code>
     *
     * <pre>
     *新值
     * </pre>
     */
    public boolean hasNewVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 new_val = 2;</code>
     *
     * <pre>
     *新值
     * </pre>
     */
    public int getNewVal() {
      return newVal_;
    }

    // required .gameserver.network.protos.game.Proto_Off_Line type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private gameserver.network.protos.game.CommonProto.Proto_Off_Line type_;
    /**
     * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
     *
     * <pre>
     *类型 
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
     *
     * <pre>
     *类型 
     * </pre>
     */
    public gameserver.network.protos.game.CommonProto.Proto_Off_Line getType() {
      return type_;
    }

    private void initFields() {
      oldVal_ = 0;
      newVal_ = 0;
      type_ = gameserver.network.protos.game.CommonProto.Proto_Off_Line.LEGION_LV;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOldVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, oldVal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, newVal_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, oldVal_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, newVal_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_Player_Val_Change}
     *
     * <pre>
     *玩家数据变化
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_ChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.ProPlayerChange.internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.ProPlayerChange.internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.class, gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.Builder.class);
      }

      // Construct using gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        oldVal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        newVal_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = gameserver.network.protos.game.CommonProto.Proto_Off_Line.LEGION_LV;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.ProPlayerChange.internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_descriptor;
      }

      public gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change getDefaultInstanceForType() {
        return gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.getDefaultInstance();
      }

      public gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change build() {
        gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change buildPartial() {
        gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change result = new gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.oldVal_ = oldVal_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newVal_ = newVal_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change) {
          return mergeFrom((gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change other) {
        if (other == gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change.getDefaultInstance()) return this;
        if (other.hasOldVal()) {
          setOldVal(other.getOldVal());
        }
        if (other.hasNewVal()) {
          setNewVal(other.getNewVal());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOldVal()) {
          
          return false;
        }
        if (!hasNewVal()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.ProPlayerChange.Msg_G2C_Player_Val_Change) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 old_val = 1;
      private int oldVal_ ;
      /**
       * <code>required int32 old_val = 1;</code>
       *
       * <pre>
       *旧值
       * </pre>
       */
      public boolean hasOldVal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 old_val = 1;</code>
       *
       * <pre>
       *旧值
       * </pre>
       */
      public int getOldVal() {
        return oldVal_;
      }
      /**
       * <code>required int32 old_val = 1;</code>
       *
       * <pre>
       *旧值
       * </pre>
       */
      public Builder setOldVal(int value) {
        bitField0_ |= 0x00000001;
        oldVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 old_val = 1;</code>
       *
       * <pre>
       *旧值
       * </pre>
       */
      public Builder clearOldVal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oldVal_ = 0;
        onChanged();
        return this;
      }

      // required int32 new_val = 2;
      private int newVal_ ;
      /**
       * <code>required int32 new_val = 2;</code>
       *
       * <pre>
       *新值
       * </pre>
       */
      public boolean hasNewVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 new_val = 2;</code>
       *
       * <pre>
       *新值
       * </pre>
       */
      public int getNewVal() {
        return newVal_;
      }
      /**
       * <code>required int32 new_val = 2;</code>
       *
       * <pre>
       *新值
       * </pre>
       */
      public Builder setNewVal(int value) {
        bitField0_ |= 0x00000002;
        newVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 new_val = 2;</code>
       *
       * <pre>
       *新值
       * </pre>
       */
      public Builder clearNewVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newVal_ = 0;
        onChanged();
        return this;
      }

      // required .gameserver.network.protos.game.Proto_Off_Line type = 3;
      private gameserver.network.protos.game.CommonProto.Proto_Off_Line type_ = gameserver.network.protos.game.CommonProto.Proto_Off_Line.LEGION_LV;
      /**
       * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
       *
       * <pre>
       *类型 
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
       *
       * <pre>
       *类型 
       * </pre>
       */
      public gameserver.network.protos.game.CommonProto.Proto_Off_Line getType() {
        return type_;
      }
      /**
       * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
       *
       * <pre>
       *类型 
       * </pre>
       */
      public Builder setType(gameserver.network.protos.game.CommonProto.Proto_Off_Line value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gameserver.network.protos.game.Proto_Off_Line type = 3;</code>
       *
       * <pre>
       *类型 
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = gameserver.network.protos.game.CommonProto.Proto_Off_Line.LEGION_LV;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_G2C_Player_Val_Change)
    }

    static {
      defaultInstance = new Msg_G2C_Player_Val_Change(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_G2C_Player_Val_Change)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"game/cs-java/ProPlayerChange.proto\022\036ga" +
      "meserver.network.protos.game\032$game/cs-ja" +
      "va-share/CommonProto.proto\"{\n\031Msg_G2C_Pl" +
      "ayer_Val_Change\022\017\n\007old_val\030\001 \002(\005\022\017\n\007new_" +
      "val\030\002 \002(\005\022<\n\004type\030\003 \002(\0162..gameserver.net" +
      "work.protos.game.Proto_Off_Line"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_G2C_Player_Val_Change_descriptor,
              new java.lang.String[] { "OldVal", "NewVal", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gameserver.network.protos.game.CommonProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
