// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/cs-java/ProPassiveBuff.proto

package gameserver.network.protos.game;

public final class ProPassiveBuff {
  private ProPassiveBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gameserver.network.protos.game.Proto_PassiveBuffType}
   */
  public enum Proto_PassiveBuffType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LIST = 1;</code>
     *
     * <pre>
     *列表
     * </pre>
     */
    LIST(0, 1),
    /**
     * <code>UPDATE = 2;</code>
     *
     * <pre>
     *更新
     * </pre>
     */
    UPDATE(1, 2),
    ;

    /**
     * <code>LIST = 1;</code>
     *
     * <pre>
     *列表
     * </pre>
     */
    public static final int LIST_VALUE = 1;
    /**
     * <code>UPDATE = 2;</code>
     *
     * <pre>
     *更新
     * </pre>
     */
    public static final int UPDATE_VALUE = 2;


    public final int getNumber() { return value; }

    public static Proto_PassiveBuffType valueOf(int value) {
      switch (value) {
        case 1: return LIST;
        case 2: return UPDATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Proto_PassiveBuffType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Proto_PassiveBuffType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Proto_PassiveBuffType>() {
            public Proto_PassiveBuffType findValueByNumber(int number) {
              return Proto_PassiveBuffType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return gameserver.network.protos.game.ProPassiveBuff.getDescriptor().getEnumTypes().get(0);
    }

    private static final Proto_PassiveBuffType[] VALUES = values();

    public static Proto_PassiveBuffType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Proto_PassiveBuffType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gameserver.network.protos.game.Proto_PassiveBuffType)
  }

  public interface Msg_G2C_PassiveBuffOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;
    /**
     * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType getType();

    // repeated int32 tables = 2;
    /**
     * <code>repeated int32 tables = 2;</code>
     *
     * <pre>
     *被动Buff列表
     * </pre>
     */
    java.util.List<java.lang.Integer> getTablesList();
    /**
     * <code>repeated int32 tables = 2;</code>
     *
     * <pre>
     *被动Buff列表
     * </pre>
     */
    int getTablesCount();
    /**
     * <code>repeated int32 tables = 2;</code>
     *
     * <pre>
     *被动Buff列表
     * </pre>
     */
    int getTables(int index);

    // repeated int32 addTables = 3;
    /**
     * <code>repeated int32 addTables = 3;</code>
     *
     * <pre>
     *新添加的列表  只有type==UPDATE时候
     * </pre>
     */
    java.util.List<java.lang.Integer> getAddTablesList();
    /**
     * <code>repeated int32 addTables = 3;</code>
     *
     * <pre>
     *新添加的列表  只有type==UPDATE时候
     * </pre>
     */
    int getAddTablesCount();
    /**
     * <code>repeated int32 addTables = 3;</code>
     *
     * <pre>
     *新添加的列表  只有type==UPDATE时候
     * </pre>
     */
    int getAddTables(int index);

    // repeated int32 delTables = 4;
    /**
     * <code>repeated int32 delTables = 4;</code>
     *
     * <pre>
     *删除的列表	只有type==UPDATE时候
     * </pre>
     */
    java.util.List<java.lang.Integer> getDelTablesList();
    /**
     * <code>repeated int32 delTables = 4;</code>
     *
     * <pre>
     *删除的列表	只有type==UPDATE时候
     * </pre>
     */
    int getDelTablesCount();
    /**
     * <code>repeated int32 delTables = 4;</code>
     *
     * <pre>
     *删除的列表	只有type==UPDATE时候
     * </pre>
     */
    int getDelTables(int index);

    // repeated int32 buffType = 5;
    /**
     * <code>repeated int32 buffType = 5;</code>
     */
    java.util.List<java.lang.Integer> getBuffTypeList();
    /**
     * <code>repeated int32 buffType = 5;</code>
     */
    int getBuffTypeCount();
    /**
     * <code>repeated int32 buffType = 5;</code>
     */
    int getBuffType(int index);

    // repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    java.util.List<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain> 
        getBuffEffectList();
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain getBuffEffect(int index);
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    int getBuffEffectCount();
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    java.util.List<? extends gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder> 
        getBuffEffectOrBuilderList();
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder getBuffEffectOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_PassiveBuff}
   *
   * <pre>
   * 发送PassiveBuff列表
   * </pre>
   */
  public static final class Msg_G2C_PassiveBuff extends
      com.google.protobuf.GeneratedMessage
      implements Msg_G2C_PassiveBuffOrBuilder {
    // Use Msg_G2C_PassiveBuff.newBuilder() to construct.
    private Msg_G2C_PassiveBuff(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Msg_G2C_PassiveBuff(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Msg_G2C_PassiveBuff defaultInstance;
    public static Msg_G2C_PassiveBuff getDefaultInstance() {
      return defaultInstance;
    }

    public Msg_G2C_PassiveBuff getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Msg_G2C_PassiveBuff(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType value = gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                tables_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              tables_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                tables_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                tables_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                addTables_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              addTables_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                addTables_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                addTables_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                delTables_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              delTables_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                delTables_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                delTables_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                buffType_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              buffType_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                buffType_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                buffType_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                buffEffect_ = new java.util.ArrayList<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain>();
                mutable_bitField0_ |= 0x00000020;
              }
              buffEffect_.add(input.readMessage(gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          tables_ = java.util.Collections.unmodifiableList(tables_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          addTables_ = java.util.Collections.unmodifiableList(addTables_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          delTables_ = java.util.Collections.unmodifiableList(delTables_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          buffType_ = java.util.Collections.unmodifiableList(buffType_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          buffEffect_ = java.util.Collections.unmodifiableList(buffEffect_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.class, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Builder.class);
    }

    public static com.google.protobuf.Parser<Msg_G2C_PassiveBuff> PARSER =
        new com.google.protobuf.AbstractParser<Msg_G2C_PassiveBuff>() {
      public Msg_G2C_PassiveBuff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg_G2C_PassiveBuff(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg_G2C_PassiveBuff> getParserForType() {
      return PARSER;
    }

    public interface Msg_PassiveGainOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 value = 1;
      /**
       * <code>required int32 value = 1;</code>
       */
      boolean hasValue();
      /**
       * <code>required int32 value = 1;</code>
       */
      int getValue();

      // required float value_f = 2;
      /**
       * <code>required float value_f = 2;</code>
       */
      boolean hasValueF();
      /**
       * <code>required float value_f = 2;</code>
       */
      float getValueF();
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain}
     */
    public static final class Msg_PassiveGain extends
        com.google.protobuf.GeneratedMessage
        implements Msg_PassiveGainOrBuilder {
      // Use Msg_PassiveGain.newBuilder() to construct.
      private Msg_PassiveGain(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Msg_PassiveGain(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Msg_PassiveGain defaultInstance;
      public static Msg_PassiveGain getDefaultInstance() {
        return defaultInstance;
      }

      public Msg_PassiveGain getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Msg_PassiveGain(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                value_ = input.readInt32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                valueF_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.class, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder.class);
      }

      public static com.google.protobuf.Parser<Msg_PassiveGain> PARSER =
          new com.google.protobuf.AbstractParser<Msg_PassiveGain>() {
        public Msg_PassiveGain parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Msg_PassiveGain(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Msg_PassiveGain> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private int value_;
      /**
       * <code>required int32 value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }

      // required float value_f = 2;
      public static final int VALUE_F_FIELD_NUMBER = 2;
      private float valueF_;
      /**
       * <code>required float value_f = 2;</code>
       */
      public boolean hasValueF() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float value_f = 2;</code>
       */
      public float getValueF() {
        return valueF_;
      }

      private void initFields() {
        value_ = 0;
        valueF_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValueF()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, value_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, valueF_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, value_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, valueF_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.class, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder.class);
        }

        // Construct using gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          value_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          valueF_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_descriptor;
        }

        public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain getDefaultInstanceForType() {
          return gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.getDefaultInstance();
        }

        public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain build() {
          gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain buildPartial() {
          gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain result = new gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.value_ = value_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.valueF_ = valueF_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain) {
            return mergeFrom((gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain other) {
          if (other == gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.getDefaultInstance()) return this;
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          if (other.hasValueF()) {
            setValueF(other.getValueF());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasValue()) {
            
            return false;
          }
          if (!hasValueF()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 value = 1;
        private int value_ ;
        /**
         * <code>required int32 value = 1;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 value = 1;</code>
         */
        public int getValue() {
          return value_;
        }
        /**
         * <code>required int32 value = 1;</code>
         */
        public Builder setValue(int value) {
          bitField0_ |= 0x00000001;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 value = 1;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0;
          onChanged();
          return this;
        }

        // required float value_f = 2;
        private float valueF_ ;
        /**
         * <code>required float value_f = 2;</code>
         */
        public boolean hasValueF() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required float value_f = 2;</code>
         */
        public float getValueF() {
          return valueF_;
        }
        /**
         * <code>required float value_f = 2;</code>
         */
        public Builder setValueF(float value) {
          bitField0_ |= 0x00000002;
          valueF_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float value_f = 2;</code>
         */
        public Builder clearValueF() {
          bitField0_ = (bitField0_ & ~0x00000002);
          valueF_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain)
      }

      static {
        defaultInstance = new Msg_PassiveGain(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain)
    }

    private int bitField0_;
    // required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType type_;
    /**
     * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    public gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType getType() {
      return type_;
    }

    // repeated int32 tables = 2;
    public static final int TABLES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> tables_;
    /**
     * <code>repeated int32 tables = 2;</code>
     *
     * <pre>
     *被动Buff列表
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getTablesList() {
      return tables_;
    }
    /**
     * <code>repeated int32 tables = 2;</code>
     *
     * <pre>
     *被动Buff列表
     * </pre>
     */
    public int getTablesCount() {
      return tables_.size();
    }
    /**
     * <code>repeated int32 tables = 2;</code>
     *
     * <pre>
     *被动Buff列表
     * </pre>
     */
    public int getTables(int index) {
      return tables_.get(index);
    }

    // repeated int32 addTables = 3;
    public static final int ADDTABLES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> addTables_;
    /**
     * <code>repeated int32 addTables = 3;</code>
     *
     * <pre>
     *新添加的列表  只有type==UPDATE时候
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getAddTablesList() {
      return addTables_;
    }
    /**
     * <code>repeated int32 addTables = 3;</code>
     *
     * <pre>
     *新添加的列表  只有type==UPDATE时候
     * </pre>
     */
    public int getAddTablesCount() {
      return addTables_.size();
    }
    /**
     * <code>repeated int32 addTables = 3;</code>
     *
     * <pre>
     *新添加的列表  只有type==UPDATE时候
     * </pre>
     */
    public int getAddTables(int index) {
      return addTables_.get(index);
    }

    // repeated int32 delTables = 4;
    public static final int DELTABLES_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> delTables_;
    /**
     * <code>repeated int32 delTables = 4;</code>
     *
     * <pre>
     *删除的列表	只有type==UPDATE时候
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getDelTablesList() {
      return delTables_;
    }
    /**
     * <code>repeated int32 delTables = 4;</code>
     *
     * <pre>
     *删除的列表	只有type==UPDATE时候
     * </pre>
     */
    public int getDelTablesCount() {
      return delTables_.size();
    }
    /**
     * <code>repeated int32 delTables = 4;</code>
     *
     * <pre>
     *删除的列表	只有type==UPDATE时候
     * </pre>
     */
    public int getDelTables(int index) {
      return delTables_.get(index);
    }

    // repeated int32 buffType = 5;
    public static final int BUFFTYPE_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> buffType_;
    /**
     * <code>repeated int32 buffType = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getBuffTypeList() {
      return buffType_;
    }
    /**
     * <code>repeated int32 buffType = 5;</code>
     */
    public int getBuffTypeCount() {
      return buffType_.size();
    }
    /**
     * <code>repeated int32 buffType = 5;</code>
     */
    public int getBuffType(int index) {
      return buffType_.get(index);
    }

    // repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;
    public static final int BUFFEFFECT_FIELD_NUMBER = 6;
    private java.util.List<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain> buffEffect_;
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    public java.util.List<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain> getBuffEffectList() {
      return buffEffect_;
    }
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    public java.util.List<? extends gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder> 
        getBuffEffectOrBuilderList() {
      return buffEffect_;
    }
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    public int getBuffEffectCount() {
      return buffEffect_.size();
    }
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain getBuffEffect(int index) {
      return buffEffect_.get(index);
    }
    /**
     * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
     */
    public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder getBuffEffectOrBuilder(
        int index) {
      return buffEffect_.get(index);
    }

    private void initFields() {
      type_ = gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType.LIST;
      tables_ = java.util.Collections.emptyList();
      addTables_ = java.util.Collections.emptyList();
      delTables_ = java.util.Collections.emptyList();
      buffType_ = java.util.Collections.emptyList();
      buffEffect_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBuffEffectCount(); i++) {
        if (!getBuffEffect(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < tables_.size(); i++) {
        output.writeInt32(2, tables_.get(i));
      }
      for (int i = 0; i < addTables_.size(); i++) {
        output.writeInt32(3, addTables_.get(i));
      }
      for (int i = 0; i < delTables_.size(); i++) {
        output.writeInt32(4, delTables_.get(i));
      }
      for (int i = 0; i < buffType_.size(); i++) {
        output.writeInt32(5, buffType_.get(i));
      }
      for (int i = 0; i < buffEffect_.size(); i++) {
        output.writeMessage(6, buffEffect_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tables_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(tables_.get(i));
        }
        size += dataSize;
        size += 1 * getTablesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addTables_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(addTables_.get(i));
        }
        size += dataSize;
        size += 1 * getAddTablesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < delTables_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(delTables_.get(i));
        }
        size += dataSize;
        size += 1 * getDelTablesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < buffType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(buffType_.get(i));
        }
        size += dataSize;
        size += 1 * getBuffTypeList().size();
      }
      for (int i = 0; i < buffEffect_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, buffEffect_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gameserver.network.protos.game.Msg_G2C_PassiveBuff}
     *
     * <pre>
     * 发送PassiveBuff列表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.class, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Builder.class);
      }

      // Construct using gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuffEffectFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType.LIST;
        bitField0_ = (bitField0_ & ~0x00000001);
        tables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        addTables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        delTables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        buffType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        if (buffEffectBuilder_ == null) {
          buffEffect_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          buffEffectBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gameserver.network.protos.game.ProPassiveBuff.internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor;
      }

      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff getDefaultInstanceForType() {
        return gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.getDefaultInstance();
      }

      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff build() {
        gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff buildPartial() {
        gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff result = new gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          tables_ = java.util.Collections.unmodifiableList(tables_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tables_ = tables_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          addTables_ = java.util.Collections.unmodifiableList(addTables_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.addTables_ = addTables_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          delTables_ = java.util.Collections.unmodifiableList(delTables_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.delTables_ = delTables_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          buffType_ = java.util.Collections.unmodifiableList(buffType_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.buffType_ = buffType_;
        if (buffEffectBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            buffEffect_ = java.util.Collections.unmodifiableList(buffEffect_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.buffEffect_ = buffEffect_;
        } else {
          result.buffEffect_ = buffEffectBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff) {
          return mergeFrom((gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff other) {
        if (other == gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.tables_.isEmpty()) {
          if (tables_.isEmpty()) {
            tables_ = other.tables_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTablesIsMutable();
            tables_.addAll(other.tables_);
          }
          onChanged();
        }
        if (!other.addTables_.isEmpty()) {
          if (addTables_.isEmpty()) {
            addTables_ = other.addTables_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAddTablesIsMutable();
            addTables_.addAll(other.addTables_);
          }
          onChanged();
        }
        if (!other.delTables_.isEmpty()) {
          if (delTables_.isEmpty()) {
            delTables_ = other.delTables_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDelTablesIsMutable();
            delTables_.addAll(other.delTables_);
          }
          onChanged();
        }
        if (!other.buffType_.isEmpty()) {
          if (buffType_.isEmpty()) {
            buffType_ = other.buffType_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureBuffTypeIsMutable();
            buffType_.addAll(other.buffType_);
          }
          onChanged();
        }
        if (buffEffectBuilder_ == null) {
          if (!other.buffEffect_.isEmpty()) {
            if (buffEffect_.isEmpty()) {
              buffEffect_ = other.buffEffect_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureBuffEffectIsMutable();
              buffEffect_.addAll(other.buffEffect_);
            }
            onChanged();
          }
        } else {
          if (!other.buffEffect_.isEmpty()) {
            if (buffEffectBuilder_.isEmpty()) {
              buffEffectBuilder_.dispose();
              buffEffectBuilder_ = null;
              buffEffect_ = other.buffEffect_;
              bitField0_ = (bitField0_ & ~0x00000020);
              buffEffectBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBuffEffectFieldBuilder() : null;
            } else {
              buffEffectBuilder_.addAllMessages(other.buffEffect_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getBuffEffectCount(); i++) {
          if (!getBuffEffect(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;
      private gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType type_ = gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType.LIST;
      /**
       * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType getType() {
        return type_;
      }
      /**
       * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public Builder setType(gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gameserver.network.protos.game.Proto_PassiveBuffType type = 1;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = gameserver.network.protos.game.ProPassiveBuff.Proto_PassiveBuffType.LIST;
        onChanged();
        return this;
      }

      // repeated int32 tables = 2;
      private java.util.List<java.lang.Integer> tables_ = java.util.Collections.emptyList();
      private void ensureTablesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tables_ = new java.util.ArrayList<java.lang.Integer>(tables_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getTablesList() {
        return java.util.Collections.unmodifiableList(tables_);
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public int getTablesCount() {
        return tables_.size();
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public int getTables(int index) {
        return tables_.get(index);
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public Builder setTables(
          int index, int value) {
        ensureTablesIsMutable();
        tables_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public Builder addTables(int value) {
        ensureTablesIsMutable();
        tables_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public Builder addAllTables(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTablesIsMutable();
        super.addAll(values, tables_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 tables = 2;</code>
       *
       * <pre>
       *被动Buff列表
       * </pre>
       */
      public Builder clearTables() {
        tables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated int32 addTables = 3;
      private java.util.List<java.lang.Integer> addTables_ = java.util.Collections.emptyList();
      private void ensureAddTablesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          addTables_ = new java.util.ArrayList<java.lang.Integer>(addTables_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getAddTablesList() {
        return java.util.Collections.unmodifiableList(addTables_);
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public int getAddTablesCount() {
        return addTables_.size();
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public int getAddTables(int index) {
        return addTables_.get(index);
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public Builder setAddTables(
          int index, int value) {
        ensureAddTablesIsMutable();
        addTables_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public Builder addAddTables(int value) {
        ensureAddTablesIsMutable();
        addTables_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public Builder addAllAddTables(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAddTablesIsMutable();
        super.addAll(values, addTables_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 addTables = 3;</code>
       *
       * <pre>
       *新添加的列表  只有type==UPDATE时候
       * </pre>
       */
      public Builder clearAddTables() {
        addTables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // repeated int32 delTables = 4;
      private java.util.List<java.lang.Integer> delTables_ = java.util.Collections.emptyList();
      private void ensureDelTablesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          delTables_ = new java.util.ArrayList<java.lang.Integer>(delTables_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getDelTablesList() {
        return java.util.Collections.unmodifiableList(delTables_);
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public int getDelTablesCount() {
        return delTables_.size();
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public int getDelTables(int index) {
        return delTables_.get(index);
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public Builder setDelTables(
          int index, int value) {
        ensureDelTablesIsMutable();
        delTables_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public Builder addDelTables(int value) {
        ensureDelTablesIsMutable();
        delTables_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public Builder addAllDelTables(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDelTablesIsMutable();
        super.addAll(values, delTables_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 delTables = 4;</code>
       *
       * <pre>
       *删除的列表	只有type==UPDATE时候
       * </pre>
       */
      public Builder clearDelTables() {
        delTables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated int32 buffType = 5;
      private java.util.List<java.lang.Integer> buffType_ = java.util.Collections.emptyList();
      private void ensureBuffTypeIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          buffType_ = new java.util.ArrayList<java.lang.Integer>(buffType_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getBuffTypeList() {
        return java.util.Collections.unmodifiableList(buffType_);
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public int getBuffTypeCount() {
        return buffType_.size();
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public int getBuffType(int index) {
        return buffType_.get(index);
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public Builder setBuffType(
          int index, int value) {
        ensureBuffTypeIsMutable();
        buffType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public Builder addBuffType(int value) {
        ensureBuffTypeIsMutable();
        buffType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public Builder addAllBuffType(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBuffTypeIsMutable();
        super.addAll(values, buffType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 buffType = 5;</code>
       */
      public Builder clearBuffType() {
        buffType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;
      private java.util.List<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain> buffEffect_ =
        java.util.Collections.emptyList();
      private void ensureBuffEffectIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          buffEffect_ = new java.util.ArrayList<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain>(buffEffect_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder> buffEffectBuilder_;

      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public java.util.List<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain> getBuffEffectList() {
        if (buffEffectBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buffEffect_);
        } else {
          return buffEffectBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public int getBuffEffectCount() {
        if (buffEffectBuilder_ == null) {
          return buffEffect_.size();
        } else {
          return buffEffectBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain getBuffEffect(int index) {
        if (buffEffectBuilder_ == null) {
          return buffEffect_.get(index);
        } else {
          return buffEffectBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder setBuffEffect(
          int index, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain value) {
        if (buffEffectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuffEffectIsMutable();
          buffEffect_.set(index, value);
          onChanged();
        } else {
          buffEffectBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder setBuffEffect(
          int index, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder builderForValue) {
        if (buffEffectBuilder_ == null) {
          ensureBuffEffectIsMutable();
          buffEffect_.set(index, builderForValue.build());
          onChanged();
        } else {
          buffEffectBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder addBuffEffect(gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain value) {
        if (buffEffectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuffEffectIsMutable();
          buffEffect_.add(value);
          onChanged();
        } else {
          buffEffectBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder addBuffEffect(
          int index, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain value) {
        if (buffEffectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuffEffectIsMutable();
          buffEffect_.add(index, value);
          onChanged();
        } else {
          buffEffectBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder addBuffEffect(
          gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder builderForValue) {
        if (buffEffectBuilder_ == null) {
          ensureBuffEffectIsMutable();
          buffEffect_.add(builderForValue.build());
          onChanged();
        } else {
          buffEffectBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder addBuffEffect(
          int index, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder builderForValue) {
        if (buffEffectBuilder_ == null) {
          ensureBuffEffectIsMutable();
          buffEffect_.add(index, builderForValue.build());
          onChanged();
        } else {
          buffEffectBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder addAllBuffEffect(
          java.lang.Iterable<? extends gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain> values) {
        if (buffEffectBuilder_ == null) {
          ensureBuffEffectIsMutable();
          super.addAll(values, buffEffect_);
          onChanged();
        } else {
          buffEffectBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder clearBuffEffect() {
        if (buffEffectBuilder_ == null) {
          buffEffect_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          buffEffectBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public Builder removeBuffEffect(int index) {
        if (buffEffectBuilder_ == null) {
          ensureBuffEffectIsMutable();
          buffEffect_.remove(index);
          onChanged();
        } else {
          buffEffectBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder getBuffEffectBuilder(
          int index) {
        return getBuffEffectFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder getBuffEffectOrBuilder(
          int index) {
        if (buffEffectBuilder_ == null) {
          return buffEffect_.get(index);  } else {
          return buffEffectBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public java.util.List<? extends gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder> 
           getBuffEffectOrBuilderList() {
        if (buffEffectBuilder_ != null) {
          return buffEffectBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buffEffect_);
        }
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder addBuffEffectBuilder() {
        return getBuffEffectFieldBuilder().addBuilder(
            gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.getDefaultInstance());
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder addBuffEffectBuilder(
          int index) {
        return getBuffEffectFieldBuilder().addBuilder(
            index, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.getDefaultInstance());
      }
      /**
       * <code>repeated .gameserver.network.protos.game.Msg_G2C_PassiveBuff.Msg_PassiveGain buffEffect = 6;</code>
       */
      public java.util.List<gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder> 
           getBuffEffectBuilderList() {
        return getBuffEffectFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder> 
          getBuffEffectFieldBuilder() {
        if (buffEffectBuilder_ == null) {
          buffEffectBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGain.Builder, gameserver.network.protos.game.ProPassiveBuff.Msg_G2C_PassiveBuff.Msg_PassiveGainOrBuilder>(
                  buffEffect_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          buffEffect_ = null;
        }
        return buffEffectBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gameserver.network.protos.game.Msg_G2C_PassiveBuff)
    }

    static {
      defaultInstance = new Msg_G2C_PassiveBuff(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gameserver.network.protos.game.Msg_G2C_PassiveBuff)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!game/cs-java/ProPassiveBuff.proto\022\036gam" +
      "eserver.network.protos.game\"\256\002\n\023Msg_G2C_" +
      "PassiveBuff\022C\n\004type\030\001 \002(\01625.gameserver.n" +
      "etwork.protos.game.Proto_PassiveBuffType" +
      "\022\016\n\006tables\030\002 \003(\005\022\021\n\taddTables\030\003 \003(\005\022\021\n\td" +
      "elTables\030\004 \003(\005\022\020\n\010buffType\030\005 \003(\005\022W\n\nbuff" +
      "Effect\030\006 \003(\0132C.gameserver.network.protos" +
      ".game.Msg_G2C_PassiveBuff.Msg_PassiveGai" +
      "n\0321\n\017Msg_PassiveGain\022\r\n\005value\030\001 \002(\005\022\017\n\007v" +
      "alue_f\030\002 \002(\002*-\n\025Proto_PassiveBuffType\022\010\n",
      "\004LIST\020\001\022\n\n\006UPDATE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor,
              new java.lang.String[] { "Type", "Tables", "AddTables", "DelTables", "BuffType", "BuffEffect", });
          internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_descriptor =
            internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_descriptor.getNestedTypes().get(0);
          internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gameserver_network_protos_game_Msg_G2C_PassiveBuff_Msg_PassiveGain_descriptor,
              new java.lang.String[] { "Value", "ValueF", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
